name: Publish Dockerhub
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      id: get_version
      run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: by6756/mango
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,0.30.41"
        platforms: linux/amd64,linux/arm64
        cache: true
